name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true

jobs:
  test-ci:
    name: Test CI - GraalVM 23.1.0 For JDK21 on ubuntu-latest
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download Source and build Native Image
        run: |
          git clone -b update-graalvm-jdk21 https://github.com/linghengqian/shardingsphere.git
          cd ./shardingsphere/
          git reset --hard f168011d597c4da21c4b52bd35f9ef9af1b45b96
          ./mvnw -am -pl distribution/proxy-native -T1C -e -Prelease.native -DskipTests clean package
